server:
  port: 8081
spring:
  application:
    name: tax-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tax?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 192.168.245.154:8848
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
